import jsPDF from "jspdf";

export interface ExportData {
  planner: string;
  architecture: string;
  database: string;
  api: string;
  folder: string;
  blueprint: string;
  readme: string;
  sql: string;
  message: string;
}

export const exportUtils = {

  // ==========================
  // MARKDOWN EXPORT
  // ==========================

  downloadMarkdown(data: ExportData) {

    const markdown = `# AI CTO Blueprint

**Project:** ${data.message}

**Generated:** ${new Date().toLocaleString()}

---

# 📋 Development Plan

${data.planner}

---

# 🏗️ System Architecture

${data.architecture}

---

# 🗄️ Database Design

${data.database}

---

# 🔌 API Design

${data.api}

---

# 📁 Folder Structure

${data.folder}

---

# 📄 Software Blueprint

${data.blueprint}

---

# 📘 README.md

${data.readme}

---

# 🗄️ SQL Schema

${data.sql}

---

Generated by AI CTO Agent
`;

    const blob = new Blob(
      [markdown],
      {
        type: "text/markdown",
      }
    );

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;

    a.download = `AI_CTO_${Date.now()}.md`;

    document.body.appendChild(a);

    a.click();

    document.body.removeChild(a);

    URL.revokeObjectURL(url);
  },

  // ==========================
  // PDF EXPORT
  // ==========================

  downloadPDF(data: ExportData) {

    const doc = new jsPDF();

    let y = 20;

    const pageWidth = doc.internal.pageSize.getWidth();

    const pageHeight = doc.internal.pageSize.getHeight();

    const margin = 15;

    const width = pageWidth - margin * 2;

    const addHeading = (text: string) => {

      if (y > pageHeight - 30) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(16);

      doc.setFont("helvetica", "bold");

      doc.text(text, margin, y);

      y += 8;

    };

    const addContent = (text: string) => {

      doc.setFontSize(10);

      doc.setFont("helvetica", "normal");

      const lines = doc.splitTextToSize(text, width);

      lines.forEach((line: string) => {

        if (y > pageHeight - 20) {

          doc.addPage();

          y = 20;

        }

        doc.text(line, margin, y);

        y += 5;

      });

      y += 8;

    };

    doc.setFontSize(22);

    doc.setFont("helvetica", "bold");

    doc.text("AI CTO Blueprint", margin, y);

    y += 12;

    doc.setFontSize(11);

    doc.setFont("helvetica", "normal");

    doc.text(`Project : ${data.message}`, margin, y);

    y += 8;

    doc.text(new Date().toLocaleString(), margin, y);

    y += 15;

    addHeading("Development Plan");
    addContent(data.planner);

    addHeading("Architecture");
    addContent(data.architecture);

    addHeading("Database");
    addContent(data.database);

    addHeading("API Design");
    addContent(data.api);

    addHeading("Project Structure");
    addContent(data.folder);

    addHeading("Software Blueprint");
    addContent(data.blueprint);

    addHeading("README.md");
    addContent(data.readme);

    addHeading("SQL Schema");
    addContent(data.sql);
        // Footer

    const pages = doc.getNumberOfPages();

    for (let i = 1; i <= pages; i++) {

      doc.setPage(i);

      doc.setFontSize(8);

      doc.setTextColor(120);

      doc.text(
        `Generated by AI CTO Agent | Page ${i} of ${pages}`,
        pageWidth / 2,
        pageHeight - 10,
        {
          align: "center",
        }
      );

    }

    doc.save(`AI_CTO_${Date.now()}.pdf`);

  },

  // ==========================
  // COPY TO CLIPBOARD
  // ==========================

  async copyToClipboard(data: ExportData) {

    const content = `

AI CTO Blueprint

======================================

Project

${data.message}

======================================

Development Plan

${data.planner}

======================================

Architecture

${data.architecture}

======================================

Database

${data.database}

======================================

API Design

${data.api}

======================================

Folder Structure

${data.folder}

======================================

Software Blueprint

${data.blueprint}

======================================

README.md

${data.readme}

======================================

SQL Schema

${data.sql}

======================================

Generated by AI CTO Agent

`;

    await navigator.clipboard.writeText(content);

  },

};